# 预备知识

tf.where(条件语句，真返回A，假返回B)

    a = tf.constant([1,2,3,1,1,1])

    b = tf.constant([0,1,3,4,5])


若a>b，返回a`对应位置`的元素，否则返回b`对应位置`的元素

greater比较对应元素

    c = tf.where(tf.greater(a,b),a,b)
    【out:】 tf.Tensor([1 2 3 4 5],shape=(5),dtype=int32)
    
 ----------

tf.random.RandomState.rand(维度)
返回一个[0,1)之间的随机数
维度为空、返回张量

    import numpy as np
    rdm = np.random.RandomState(seed=1)#seed常数每次生成的随机数相同
    a = rdm.rand() #返回一个随机标量
    b = rdm.rand(2,3)#返回一个2行3列的随机数矩阵
    print("a",a)
    print("b",b)
    【out:】
    a:0.417022...........
    b:[[7.20  .. ...],[.. .. ..]]
------

    np.vstack()
    将两个数组按垂直方向叠加
    a = np.array([1,2,3])
    b = np.array([4,5,6])
    c = np.vstack((a,b))
    print("c:",c)
    【out:】
    c:
    [[1 2 3],
    [4 5 6]]
----------

    np.mgrid[] .ravel np.c_[]可以生成网格坐标点
    
    np.mgrid[起始值：结束值：步长，重复。。。] [)
    返回若干组维度相同的等差数组
    
    
    np.ravel() #把x变成一维数组
    
    np.c_[] 使返回的间隔数值点配对输出
    np.c_[数组1，数组2，...]
    
    x,y = np.mgrid[1:3:1,2:4:0.5]
    grid = np.c_[x.ravel(),y.ravel()]
    print('x',x)
    print('y',y)
    print('grid:\n',grid)
    【out:】
    x = [[1. 1. 1. 1.]
        [2. 2. 2. 2.]]
    y = [[2. 2.5 3. 3.5]
        [2. 2.5 3. 3.5]]
    grid:（竖着看）
    [[1.2.]
    [1. 2.5]
    [1.3.]
    [1.3.5]
    [2.2.]
    [2.2.5]
    [2. 3.]
    [2.3.5]]
    

## 指数衰减学习率
指数衰减学习率 = 初始学习率 * 学习率衰减率 ** （当前轮数 / 多少轮衰减一次）
## sigmoid函数  -- 映射到 0~1
特点：
+ 易造成梯度消失
+ 输出非0均值，收敛慢
+ 幂运算复杂，训练时间长
## tanh函数 0均值 
## Relu -- 收敛速度远大于上面两者

# 激活函数
对初学者的建议：
+ 首选Relu激活函数
+ 学习率设置较小值
+ 输入特征标准化 、 *即让输入特征满足以0为均值，1为标准差的正态分布*
+ 初始参数中心化，即让随机生成的参数满足以0为均值，$$\sqrt{{2}\over{当前层输入特征个数}}$$为标准差的正态分布

# 损失函数
预测值y与已知答案y_之间的差距
## 1.均方误差mse （Mean Squared Errot）
MSE(y_,y) = $\sum{(y-y_ )}^2 \over n$

    loss_mse = tf.reduce_mean(tf.square(y_ - y))
*当使用均方误差mse、默认认为预测多了和预测少了损失是一样的，但是实际上，预测多了损失的可能是成本，预测少了损失的可能是利润。利润和成本往往不相等*
## 2.自定义
如预测酸奶销量、酸奶成本COST1元，利润PROFIT99元。预测少了损失利润99元，预测少了损失成本1元。所以希望生成的预测函数往多了预测
loss_zdy = tf.reduce_sum(tf where :((tf.greater(y,y_),cost(y-y_),profit(y_-y)))

## 3.交叉熵 ce (Cross Entropy)
交叉熵表示两个概率分布之间的距离，交叉熵越大，两个概率分布越远。

###  H(y_,y) = - $\sum{y\_ * ln y}$

eg.二分类：
已知答案y_ = (1,0)表示第一种情况发生的概率为1，第二种情况发生的概率0，

预测y1 = (0.6,0.4) y2 = (0.8,0.2)哪个更接近标准答案y_?

    答：H1((1,0),(0.6,0.4)) = 0.511
    H2 = 0.223
    H1 > H2
    所以y2预测更准
    
    loss_ce1 = tf.losses.categorical_crossentropy([1,0],[0.6,0.4])

# softmax与交叉熵结合
 输出先经过softmax函数，再计算y与y_的交叉熵损失函数
 `tf.nn.softmax_cross_entropy_with_logits(y_,y)`
 
     y_ = np..array([[1 0 0],[0 1 0],[0 0 1],[1 0 0],[0 1 0]])
     y = ...
     y_pro = tf.nn.softnax(y)
     # 分布计算
     loss_ce1 = tf.losses.categorical_crossentropy(y_,y_pro)
     
     # 综合计算
     loss_ce2 = tf.nn.softmax_cross_entropy_with_logits(y_,y)
     计算结果loss_ce1 = loss_ce2