In [2]:
import tensorflow as tf
import numpy as np

SEED = 23455
COST = 1
PROFIT = 99

rdm = np.random.RandomState(seed=SEED)#生成[0,1)的随机数
# 生成32行两列的输入特征x
x = rdm.rand(32,2)
# 生成噪声[0,1)/10 = [0,0.1)
# rand()：生成0~1的随机数
# y_是标准答案
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1,x2) in x]
print("y_:\n",y_)
x = tf.cast(x,dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2,1],stddev=1,seed=1))
epoch = 15000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        # 前向传播计算结果y
        y = tf.matmul(x,w1)
        #loss_mse = tf.reduce_mean(tf.square(y_ -y))
        # tf.where(condition, x = None, y = None, name = None)
        # condition判定返回, condition是True，选择x；condition是False，选择y。
        loss_zdy = tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_) * COST,(y_ - y) * PROFIT))
        
    # 损失函数对待训练参数w1求偏导
    grads = tape.gradient(loss_zdy,w1)
    # w1自更新
    w1.assign_sub(lr * grads)
    
    if epoch % 500 == 0:
        print("After %d training steps, w1 is " % (epoch))
        print(w1.numpy(),"\n")
print("Final w1 is: ",w1.numpy())

# 自定义损失函数
# 酸奶成本1元， 酸奶利润99元
# 成本很低，利润很高，人们希望多预测些，生成模型系数大于1，往多了预测
      

y_:
 [[0.969797861054287], [1.1634604857835003], [1.1942714411690643], [0.5384488448601839], [0.8632760602061649], [0.8339321949148727], [0.9280893354024469], [1.6879345369421652], [0.9036674505700479], [0.512956535191759], [0.7844252375973886], [1.299175094270699], [1.0919817282657285], [1.0880495166868347], [1.1734589741814216], [1.3098158421478576], [1.2387201482616108], [0.8289679938936613], [1.3550486329517144], [1.578666175492443], [0.7524305484165053], [0.7326318868381032], [1.2449966435046544], [0.788097599402105], [1.5577488607336392], [0.3889256997930456], [1.0277860551407527], [0.6104042277890978], [0.8594808823356304], [0.8810757430061307], [1.1456401959033111], [0.1907476486033659]]
After 0 training steps, w1 is 
[[2.8786578]
 [3.2517848]] 

After 500 training steps, w1 is 
[[1.1460369]
 [1.0672572]] 

After 1000 training steps, w1 is 
[[1.1364173]
 [1.0985414]] 

After 1500 training steps, w1 is 
[[1.1267972]
 [1.1298251]] 

After 2000 training steps, w1 is 
[[1.1758107]
